// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/addpoints": {
            "post": {
                "description": "Imports charging points data from a CSV file. The CSV must contain columns for location,\nstation, and charger information. Existing records are updated (upsert behavior).\n\nRequired CSV columns:\n- loc_id: Location ID (required)\n- loc_name: Location name\n- address: Location address\n- lat: Latitude coordinate\n- long: Longitude coordinate\n- is_fast: Whether location has fast chargers (boolean)\n- charger_types: Comma-separated list of charger types\n- station_id: Station ID\n- network_id: Network ID\n- charger_id: Charger ID\n- type_id: Charger type ID\n- status: Charger status\n- power: Maximum power in kW",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Import charging points from CSV",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CSV file containing charging points data",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully imported charging points",
                        "schema": {
                            "$ref": "#/definitions/handlers.AddPointsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Missing file parameter or invalid CSV format",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - Upload error, CSV parsing error, or database error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    }
                }
            }
        },
        "/getpoint/{id}": {
            "get": {
                "description": "Retrieves detailed information about a specific charging point including\nlocation coordinates, current status, capacity, pricing, and reservation details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Points"
                ],
                "summary": "Get charging point by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Charging Point ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved charging point details",
                        "schema": {
                            "$ref": "#/definitions/handlers.PointDetailDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found - Charging point does not exist",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - Database error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    }
                }
            }
        },
        "/getpoints": {
            "get": {
                "description": "Retrieves a list of all charging points with optional filtering by status and geographic bounds.\nResults can be returned in JSON or CSV format.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "text/csv"
                ],
                "tags": [
                    "Points"
                ],
                "summary": "Get all charging points",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status (available, occupied, reserved, faulted, offline)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "json",
                        "description": "Response format (json or csv)",
                        "name": "format",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Minimum latitude for geographic filtering",
                        "name": "min_lat",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum latitude for geographic filtering",
                        "name": "max_lat",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Minimum longitude for geographic filtering",
                        "name": "min_lon",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum longitude for geographic filtering",
                        "name": "max_lon",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved list of charging points",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.PointVague"
                            }
                        }
                    },
                    "204": {
                        "description": "No Content - No charging points found matching the criteria"
                    },
                    "401": {
                        "description": "Invalid Status - Unrecognized status value",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - Database error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    }
                }
            }
        },
        "/healthcheck": {
            "get": {
                "description": "Performs a health check of the API including database connectivity verification\nand retrieval of charging point statistics. Returns system status and counts of\nonline vs offline charging points.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Check API health status",
                "responses": {
                    "200": {
                        "description": "System is healthy",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthCheckResponse"
                        }
                    },
                    "400": {
                        "description": "Database connection failed or query error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    }
                }
            }
        },
        "/newsession": {
            "post": {
                "description": "Records a new completed charging session with all relevant details including\nstart/end times, energy delivered, state of charge changes, and billing information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Create a new charging session",
                "parameters": [
                    {
                        "description": "Charging session details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.NewSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully created charging session (empty body)"
                    },
                    "400": {
                        "description": "Bad Request - Missing required fields or invalid timestamp format",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found - Charging point does not exist",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - Database error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    }
                }
            }
        },
        "/pointstatus/{pointid}/{from}/{to}": {
            "get": {
                "description": "Retrieves the history of status changes for a specific charging point within a date range.\nStatus changes are logged whenever a point transitions between states (e.g., available → charging).\nResults can be returned in JSON or CSV format.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "text/csv"
                ],
                "tags": [
                    "Points"
                ],
                "summary": "Get status change history for a charging point",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Charging Point ID",
                        "name": "pointid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "20251201",
                        "description": "Start date in YYYYMMDD format",
                        "name": "from",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "20251225",
                        "description": "End date in YYYYMMDD format (inclusive)",
                        "name": "to",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "json",
                        "description": "Response format (json or csv)",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved status change history",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.StatusChangeDTO"
                            }
                        }
                    },
                    "204": {
                        "description": "No Content - No status changes found in the specified date range"
                    },
                    "400": {
                        "description": "Bad Request - Invalid date format",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found - Charging point does not exist",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - Database error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    }
                }
            }
        },
        "/reserve/{id}": {
            "post": {
                "description": "Attempts to reserve a charging point for a specified duration.\nThe reservation duration must be between 15 and 60 minutes (defaults to 30 if not specified).\nOnly 'available' charging points can be reserved.\nThe operation is atomic and uses row-level locking to prevent race conditions.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservations"
                ],
                "summary": "Reserve a charging point",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Charging Point ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Reservation result (check status field for success/failure reason)",
                        "schema": {
                            "$ref": "#/definitions/handlers.ReserveResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Invalid point ID",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - Database error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    }
                }
            }
        },
        "/reserve/{id}/{minutes}": {
            "post": {
                "description": "Attempts to reserve a charging point for a specified duration.\nThe reservation duration must be between 15 and 60 minutes (defaults to 30 if not specified).\nOnly 'available' charging points can be reserved.\nThe operation is atomic and uses row-level locking to prevent race conditions.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservations"
                ],
                "summary": "Reserve a charging point",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Charging Point ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Reservation duration in minutes (15-60, default: 30)",
                        "name": "minutes",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Reservation result (check status field for success/failure reason)",
                        "schema": {
                            "$ref": "#/definitions/handlers.ReserveResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Invalid point ID",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - Database error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    }
                }
            }
        },
        "/resetpoints": {
            "post": {
                "description": "Performs a complete reset of the charging points database by:\n1. Deleting all existing charging sessions, reservations, chargers, stations, and locations\n2. Re-importing all data from the seed JSON file (data/parts1234.json)\n\nThis operation is atomic - if any step fails, all changes are rolled back.\nUse with caution as this will delete all existing session and reservation data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Reset all charging points to initial state",
                "responses": {
                    "200": {
                        "description": "Successfully reset all charging points",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResetPointsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - File read error, JSON parsing error, or database error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/{from}/{to}": {
            "get": {
                "description": "Retrieves all charging sessions for a specific charging point within a date range.\nSessions are ordered by start time in descending order (most recent first).\nResults can be returned in JSON or CSV format.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "text/csv"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Get charging sessions for a point",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Charging Point ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "20251201",
                        "description": "Start date in YYYYMMDD format",
                        "name": "from",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "20251225",
                        "description": "End date in YYYYMMDD format (inclusive)",
                        "name": "to",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "json",
                        "description": "Response format (json or csv)",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved charging sessions",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.SessionDTO"
                            }
                        }
                    },
                    "204": {
                        "description": "No Content - No sessions found in the specified date range"
                    },
                    "400": {
                        "description": "Bad Request - Invalid date format",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found - Charging point does not exist",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - Database error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    }
                }
            }
        },
        "/updpoint/{id}": {
            "post": {
                "description": "Updates the properties of a specific charging point including status, price, and pricing mode.\nAt least one field (status, kwhprice, or is_manual_price) must be provided.\nWhen setting kwhprice without specifying is_manual_price, it defaults to manual pricing mode.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Points"
                ],
                "summary": "Update a charging point",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Charging Point ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdatePointRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully updated charging point",
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdatePointResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Invalid input or missing required fields",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found - Charging point does not exist",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - Database error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorLogResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.AddPointsResponse": {
            "description": "Response body containing import status and row count",
            "type": "object",
            "properties": {
                "imported_rows": {
                    "description": "Number of rows successfully imported",
                    "type": "integer",
                    "example": 150
                },
                "status": {
                    "description": "Status of the import operation",
                    "type": "string",
                    "example": "OK"
                }
            }
        },
        "handlers.ErrorLogResponse": {
            "description": "Standard error response body containing details about the error occurrence",
            "type": "object",
            "properties": {
                "call": {
                    "description": "The API endpoint/URL that was called",
                    "type": "string",
                    "example": "/getpoint/123"
                },
                "debuginfo": {
                    "description": "Detailed debug information about the error",
                    "type": "string",
                    "example": "Point with ID 123 not found"
                },
                "error": {
                    "description": "Short error title/description",
                    "type": "string",
                    "example": "Not Found"
                },
                "originator": {
                    "description": "IP address or identifier of the request originator",
                    "type": "string",
                    "example": "192.168.1.100"
                },
                "return_code": {
                    "description": "HTTP status code returned",
                    "type": "integer",
                    "example": 404
                },
                "timeref": {
                    "description": "Timestamp when the error occurred (format: YYYY-MM-DD HH:MM)",
                    "type": "string",
                    "example": "2025-12-25 14:30"
                }
            }
        },
        "handlers.HealthCheckResponse": {
            "description": "Response containing system health information and charging point statistics",
            "type": "object",
            "properties": {
                "dbconnection": {
                    "description": "Database connection string (DSN)",
                    "type": "string",
                    "example": "postgres://user:***@localhost:5432/evcharging"
                },
                "n_charge_points": {
                    "description": "Total number of charging points in the system",
                    "type": "integer",
                    "example": 1500
                },
                "n_charge_points_offline": {
                    "description": "Number of offline charging points",
                    "type": "integer",
                    "example": 80
                },
                "n_charge_points_online": {
                    "description": "Number of online charging points (available, charging, reserved, malfunction)",
                    "type": "integer",
                    "example": 1420
                },
                "status": {
                    "description": "Overall system status (OK if healthy)",
                    "type": "string",
                    "example": "OK"
                }
            }
        },
        "handlers.NewSessionRequest": {
            "description": "Request body containing all details of a completed charging session",
            "type": "object",
            "required": [
                "amount",
                "endsoc",
                "endtime",
                "kwhprice",
                "pointid",
                "startsoc",
                "starttime",
                "totalkwh"
            ],
            "properties": {
                "amount": {
                    "description": "Total amount charged for the session in local currency",
                    "type": "number",
                    "example": 15.93
                },
                "endsoc": {
                    "description": "Battery state of charge at session end (percentage 0-100)",
                    "type": "integer",
                    "example": 80
                },
                "endtime": {
                    "description": "Session end time in format 'YYYY-MM-DD HH:MM'",
                    "type": "string",
                    "example": "2025-12-25 11:30"
                },
                "kwhprice": {
                    "description": "Price per kWh at the time of the session",
                    "type": "number",
                    "example": 0.35
                },
                "pointid": {
                    "description": "ID of the charging point where the session occurred",
                    "type": "string",
                    "example": "123"
                },
                "startsoc": {
                    "description": "Battery state of charge at session start (percentage 0-100)",
                    "type": "integer",
                    "example": 20
                },
                "starttime": {
                    "description": "Session start time in format 'YYYY-MM-DD HH:MM'",
                    "type": "string",
                    "example": "2025-12-25 10:00"
                },
                "totalkwh": {
                    "description": "Total energy delivered during the session in kWh",
                    "type": "number",
                    "example": 45.5
                }
            }
        },
        "handlers.PointDetailDTO": {
            "description": "Detailed response containing all information about a specific charging point",
            "type": "object",
            "properties": {
                "cap": {
                    "description": "Maximum charging capacity in kW",
                    "type": "integer",
                    "example": 22
                },
                "is_manual_price": {
                    "description": "Whether the price is manually set or dynamically calculated",
                    "type": "boolean",
                    "example": false
                },
                "kwhprice": {
                    "description": "Current price per kWh in local currency",
                    "type": "number",
                    "example": 0.35
                },
                "lat": {
                    "description": "Latitude coordinate of the charging point location",
                    "type": "string",
                    "example": "37.983810"
                },
                "lon": {
                    "description": "Longitude coordinate of the charging point location",
                    "type": "string",
                    "example": "23.727539"
                },
                "pointid": {
                    "description": "Unique identifier of the charging point",
                    "type": "string",
                    "example": "123"
                },
                "reservationendtime": {
                    "description": "End time of current reservation (current time if not reserved)",
                    "type": "string",
                    "example": "2025-12-25 14:30"
                },
                "status": {
                    "description": "Current status of the charging point (available, charging, reserved, malfunction, offline)",
                    "type": "string",
                    "example": "available"
                }
            }
        },
        "handlers.PointVague": {
            "description": "Summary information about a charging point for list views",
            "type": "object",
            "properties": {
                "cap": {
                    "description": "Maximum charging capacity in kW",
                    "type": "integer",
                    "example": 22
                },
                "lat": {
                    "description": "Latitude coordinate of the charging point",
                    "type": "string",
                    "example": "37.983810"
                },
                "lon": {
                    "description": "Longitude coordinate of the charging point",
                    "type": "string",
                    "example": "23.727539"
                },
                "pointid": {
                    "description": "Unique identifier of the charging point",
                    "type": "string",
                    "example": "123"
                },
                "providerΝame": {
                    "description": "Name of the charging network provider",
                    "type": "string",
                    "example": "EMPower"
                },
                "status": {
                    "description": "Current status of the charging point",
                    "type": "string",
                    "example": "available"
                }
            }
        },
        "handlers.ReserveResponseDTO": {
            "description": "Response containing the result of a reservation request",
            "type": "object",
            "properties": {
                "pointid": {
                    "description": "ID of the charging point",
                    "type": "string",
                    "example": "123"
                },
                "reservationendtime": {
                    "description": "End time of the reservation (format: YYYY-MM-DD HH:MM), or '1970-01-01 00:00' if reservation failed",
                    "type": "string",
                    "example": "2025-12-25 15:00"
                },
                "status": {
                    "description": "Result status: 'reserved' if successful, 'not_found' if point doesn't exist,\nor current status if point is not available for reservation",
                    "type": "string",
                    "example": "reserved"
                }
            }
        },
        "handlers.ResetPointsResponse": {
            "description": "Response confirming successful reset of charging points data",
            "type": "object",
            "properties": {
                "status": {
                    "description": "Status of the reset operation",
                    "type": "string",
                    "example": "OK"
                }
            }
        },
        "handlers.SessionDTO": {
            "description": "Details of a completed charging session including timing, energy, and billing information",
            "type": "object",
            "properties": {
                "amount": {
                    "description": "Total amount charged for the session in local currency",
                    "type": "number",
                    "example": 15.93
                },
                "endsoc": {
                    "description": "Battery state of charge at session end (percentage 0-100)",
                    "type": "integer",
                    "example": 80
                },
                "endtime": {
                    "description": "End time of the charging session (format: YYYY-MM-DD HH:MM)",
                    "type": "string",
                    "example": "2025-12-25 11:30"
                },
                "kwhprice": {
                    "description": "Price per kWh at the time of the session",
                    "type": "number",
                    "example": 0.35
                },
                "startsoc": {
                    "description": "Battery state of charge at session start (percentage 0-100)",
                    "type": "integer",
                    "example": 20
                },
                "starttime": {
                    "description": "Start time of the charging session (format: YYYY-MM-DD HH:MM)",
                    "type": "string",
                    "example": "2025-12-25 10:00"
                },
                "totalkwh": {
                    "description": "Total energy delivered during the session in kWh",
                    "type": "number",
                    "example": 45.5
                }
            }
        },
        "handlers.StatusChangeDTO": {
            "description": "Record of a status change event including timestamp and state transition",
            "type": "object",
            "properties": {
                "new_state": {
                    "description": "New status after the change",
                    "type": "string",
                    "example": "charging"
                },
                "old_state": {
                    "description": "Previous status before the change",
                    "type": "string",
                    "example": "available"
                },
                "timeref": {
                    "description": "Timestamp when the status change occurred (format: YYYY-MM-DD HH:MM)",
                    "type": "string",
                    "example": "2025-12-25 14:30"
                }
            }
        },
        "handlers.UpdatePointRequest": {
            "description": "Request body for updating charging point properties",
            "type": "object",
            "properties": {
                "is_manual_price": {
                    "description": "Whether the price is manually set or dynamically calculated",
                    "type": "boolean",
                    "example": true
                },
                "kwhprice": {
                    "description": "Price per kWh in the local currency",
                    "type": "number",
                    "example": 0.35
                },
                "status": {
                    "description": "Status of the charging point (available, charging, reserved, malfunction, offline)",
                    "type": "string",
                    "example": "available"
                }
            }
        },
        "handlers.UpdatePointResponse": {
            "description": "Response body containing the updated charging point details",
            "type": "object",
            "properties": {
                "is_manual_price": {
                    "description": "Indicates if the price is manually set",
                    "type": "boolean",
                    "example": true
                },
                "kwhprice": {
                    "description": "Current price per kWh",
                    "type": "number",
                    "example": 0.35
                },
                "pointid": {
                    "description": "Unique identifier of the charging point",
                    "type": "string",
                    "example": "123"
                },
                "status": {
                    "description": "Current status of the charging point",
                    "type": "string",
                    "example": "available"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "EV Charging API",
	Description:      "API for managing electric vehicle charging points",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
