project_id = "jgthimbzyhbgqnohfyqp"

[functions.api-proxy]
verify_jwt = false

[functions.api-points]
verify_jwt = false

[functions.proxy-points]
verify_jwt = false

[functions.proxy-point-details]
verify_jwt = false
