@startuml UC-FIND-NAV-main-activity

start

:Maps & Navigation Service\nshows the map;
:The system displays\nthe search filters;

:The system requests access\nto the user's location;
:The Customer (EV Driver) accepts\nor denies the access request;

if (Did the Customer (EV Driver)\nallow location access?) then (yes)
  :The Device Location Service\nretrieves the user's location;
  :The Maps & Navigation Service\ncenters the map on\nthe user's location;
else (no)
  :The Maps & Navigation Service\ncenters the map on\nthe default location;
endif


repeat
:The Customer (EV Driver)\nmodifies the search filters;
:The system updates accordingly\nthe chargers displayed\non the map;

repeat while (Has the Customer (EV Driver)\nfinished the search?) is (no) not (yes)


repeat
:The Customer (EV Driver)\nselects a charger;
:The system displays\nthe characteristics of the\nselected charger;

repeat while (Does the Customer (EV Driver)\nconfirm their selection?) is (no) not (yes)
  :The system stores\nthe selected charger\nin the session;
  :The Customer (EV Driver)\nchooses to start\nnavigation;
  :The Maps & Navigation Service\ncreates the navigation link;
  :The system redirects\nthe user to the\nnavigation platform;
  stop

@enduml