@startuml UC-FIND-NAV-alt-no-chargers

start

note left
Είσοδος από κύριο σενάριο
μετά το βήμα
Το σύστημα ενημερώνει κατάλληλα
τους φορτιστές  που εμφανίζονται
στον χάρτη
end note

if (Υπάρχουν διαθέσιμοι\nφορτιστές στον χάρτη;) then (ναι)
  :Επιστροφή στο κύριο σενάριο;
  note left
    Customer (EV Driver)
    επιλέγει φορτιστή
  end note
else (όχι)
  :Το σύστημα ενημερώνει τον χρήστη\nότι δεν βρέθηκαν φορτιστές\nγια τα τρέχοντα φίλτρα;
  :Επιστροφή στο κύριο σενάριο;
  note right
    Ο Customer (EV Driver)
    τροποποιεί τα φίλτρα αναζήτησης
  end note
endif

stop
@enduml