@startuml UC-FIND-NAV-main-activity

start

:Maps & Navigation Service\nεμφανίζει τον χάρτη;
:Το σύστημα εμφανίζει\nτα φίλτρα αναζήτησης;

:Το σύστημα ζητάει πρόσβαση\nστην τοποθεσία του χρήστη;
:Ο Customer (EV Driver) αποδέχεται\nή απορρίπτει την πρόσβαση;

if (Ο Customer (EV Driver)επέτρεψε\n την πρόσβαση στην τοποθεσία;) then (ναι)
  :Το Device Location Service\nβρίσκει την τοποθεσία του χρήστη;
  :Το Maps & Navigation Service\nτοποθετεί το κέντρο του χάρτη\nστην τοποθεσία του χρήστη;
else (όχι)
  :Το Maps & Navigation Service\nτοποθετεί το κέντρο του χάρτη\nστην προεπιλεγμένη τοποθεσία;
endif



repeat
:Ο Customer (EV Driver)\nτροποποιεί τα φίλτρα αναζήτησης;
:Το σύστημα ενημερώνει κατάλληλα\nτους φορτιστές  που εμφανίζονται\nστον χάρτη;

 repeat while (Ο Customer (EV Driver)\nολοκλήρωσε την αναζήτηση;) is (όχι) not (ναι)

repeat
:Customer (EV Driver)\nεπιλέγει φορτιστή;
:Το σύστημα εμφανίζει\nτα χαρακτηριστικά του\nεπιλεγμένου φορτιστή;

repeat while (Ο Customer (EV Driver)\nεπιβεβαιώνει την επιλογή του;) is (όχι) not (ναι)
  :Το σύστημα αποθηκεύει\nτον επιλεγμένο φορτιστή\nστη συνεδρία;
  :Ο Customer (EV Driver)\nεπιλέγει να ξεκινήσει\nτην πλοήγηση;
  :Το Maps & Navigation Service\nδημιουργεί τον σύνδεσμο πλοήγησης;
  :Το σύστημα ανακατευθύνει\nτον χρήστη στην\nπλατφόρμα πλοήγησης;
  stop


@enduml