@startuml UC-FIND-NAV-alt-no-chargers

start

note left
Entry from main scenario
after the step
"The system appropriately updates
the chargers displayed
on the map"
end note

if (Are there available\nchargers on the map?) then (yes)
  :Return to the main scenario;
  note left
    Customer (EV Driver)
    selects a charger
  end note
else (no)
  :The system informs the user\nthat no chargers were found\nfor the current filters;
  :Return to the main scenario;
  note right
    The Customer (EV Driver)
    modifies the search filters
  end note
endif

stop
@enduml