@startuml UC-FIND-NAV-alt-saved-charger

start
note left
Entry from main scenario
after the step
«Maps & Navigation Service
shows the map»
end note


:The system checks whether there is\na selected charger\nin the session;

if (Is there a selected\ncharger in the session?) then (yes)
  :The Maps & Navigation Service\ncenters the map\non the charger's location;
  :Return to the main scenario;
  note left
    «The Customer modifies
    the search filters»
  end note
else (no)
  :Return to the main scenario;
  note right
    «The system requests access
    to the user's location»
  end note
endif

stop
@enduml