@startuml UC-FIND-NAV-alt-saved-charger

start
note left
Είσοδος από κύριο σενάριο
μετά το βήμα
«Maps & Navigation Service
εμφανίζει τον χάρτη»
end note


:Το σύστημα ελέγχει αν υπάρχει\nεπιλεγμένος φορτιστής\nστη συνεδρία;

if (Υπάρχει επιλεγμένος\nφορτιστής στη συνεδρία;) then (ναι)
  :Το Maps & Navigation Service\nτοποθετεί το κέντρο του χάρτη\nστην τοποθεσία του φορτιστή;
  :Επιστροφή στο κύριο σενάριο;
  note left
    «Ο Customer τροποποιεί
    τα φίλτρα αναζήτησης»
  end note
else (όχι)
  :Επιστροφή στο κύριο σενάριο;
  note right
    «Το σύστημα ζητάει πρόσβαση
    στην τοποθεσία του χρήστη»
  end note
endif

stop
@enduml